//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModel.LifeWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LifeWebService.ILifeWebService")]
    public interface ILifeWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILifeWebService/Load", ReplyAction="http://tempuri.org/ILifeWebService/LoadResponse")]
        Domain.Game Load(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILifeWebServiceChannel : ViewModel.LifeWebService.ILifeWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LifeWebServiceClient : System.ServiceModel.ClientBase<ViewModel.LifeWebService.ILifeWebService>, ViewModel.LifeWebService.ILifeWebService {
        
        public LifeWebServiceClient() {
        }
        
        public LifeWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LifeWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifeWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifeWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Domain.Game Load(string name) {
            return base.Channel.Load(name);
        }
    }
}
