CREATE TABLE Game (
	Id INT NOT NULL IDENTITY (1,1) CONSTRAINT PK_Game PRIMARY KEY CLUSTERED,
	Name nvarchar(255) NOT NULL,
	Size int NOT NULL
)

CREATE TABLE Cell (
	Id INT NOT NULL IDENTITY (1,1) CONSTRAINT PK_Cell PRIMARY KEY CLUSTERED,
	GameId INT NOT NULL CONSTRAINT FK_Cell_Game FOREIGN KEY REFERENCES Game(Id),
	PositionX INT NOT NULL,
	PositionY INT NOT NULL 
)
